export { default as Navbar } from './Navbar'
export { default as Namebar } from './Name/Namebar'
export { default as MainForm } from './Form/MainForm'
export { default as SendForm } from './SendForm/SendForm'
export { default as Popap } from './Popup/Popup'
export { default as SimpleInputsModule } from './SimpleInput/SimpleInputsModule'